name: Lint, Build & Test workflow

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Run Code Lint
        run: |
          yarn prettier
          yarn lint

      - name: Run Test
        run: yarn test

      - name: Run Build
        run: yarn build
        